name: ThanceDemo
description: Basic authentication flow with firebase and bloc state management

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  flutter_screenutil: ^5.7.0
  google_fonts: ^5.1.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  bloc: ^8.1.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.4.1

  # Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  class_name: Lang
  arb_dir: lib/src/l10n

dev_dependencies:
  intl: ^0.17.0
  intl_utils: ^2.8.1
  lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
